### ISSUE TITLE
I don't understand how you do it so easily and check the proof

### ISSUE THREAD

**Issue by JKearnsl** [luishsr/zk-mini#1]
https://github.com/luishsr/zk-mini/blob/94107c71d6bd97f87202a33c86e5c1a53029ca64/src/circuit.rs#L108-L128

**Comment by luishsr** [comment]
Hi JKearnsl,

Thanks for following through on the tutorial and going over the code.

Indeed, most of the complexity is commonly found when translating the R1CS into Quadratic Arithmetic Program (QAP) and then the commitment schemes, which we will do soon. Also, have a look at the updated code I've pushed, where I added Finite Fields and a basic QAP. 

Also notice that in the code snippet you've shared, we are validating a hash of two inputs without using a secure hash (e.g. SHA2/3). Is that the "so easy" part you're referring to?

Let's keep in touch!

Best,
Luis

**Comment by JKearnsl** [comment]
I looked at the updated code but i still can't understand the algorithm related to the merkle tree. In this case, you are creating a proof that the element with the value 50 is on a specific path 🤥🤥

Isn't the `witness` vector a complete reflection of the entire path? Or is the task not to reveal the entire tree, for example the values ​​10 and 20 of other nodes?

Or am I already confused...

**Comment by luishsr** [comment]
In a Merkle proof, the goal is to verify that a specific value (like 50) is part of a Merkle tree without revealing the entire structure. To do this, the proof only includes the path of hashes leading from 50 up to the root, along with any sibling nodes needed for verification.

In the zkSNARK setup, the witness vector captures just this necessary information—the value 50 and its sibling hashes on the path. This avoids disclosing unrelated parts of the tree (like values 10 and 20), ensuring that only minimal data is used to verify inclusion in the tree. This approach keeps the proof efficient and private by not exposing the entire tree structure, focusing solely on the path to 50. 

Let me know if this clears things up!

**Comment by JKearnsl** [comment]
Do I understand correctly that the verifier, as part of the preliminary "setup", should receive a trusted merkle hash of the root and probably a trusted hash of the value being verified, 50?

After which, the verifier receives (in the context of the example from your code) hashes: 50, 80, 130, 30, 160 and gates: (1, 0, 2), (2, 3, 4) and verifies by building a tree, something like:

// preliminary obtained data
verifiable_hash = 50
merkle_root = 160

hash2 = h(80, verifiable_hash)
hash4 = h(hash2, 30)

assert hash4, merkle_root

Thus showing us that hash 50 is in the tree, without revealing the entire tree?

**Comment by JKearnsl** [comment]
@luishsr  If so, please let me know and we can close this issue.

**Comment by luishsr** [comment]
Hey @JKearnsl,

Yes, exactly that!

**Comment by JKearnsl** [comment]
Thanks for helping me figure this out!
